# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Jekyll for Web Designers
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference for those that are new to Jekyll."
baseurl: "/jekyll-for-designers" 
url: "http://ediworld.github.io/jekyll-for-designers"
tagline: "A basic guide to Jekyll"

# Build settings
# gems: ['jekyll-paginate','kramdown']
gems: [jekyll-paginate]
markdown: kramdown
kramdown: 
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'

permalink: /blog/:title

highlighter: rouge
#highlighter: pygments



# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
